// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(WebApplication1Context))]
    [Migration("20240819123638_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BookId");

                    b.ToTable("Book");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "F. Scott Fitzgerald",
                            Genre = "Fiction",
                            Price = 10.99m,
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            BookId = 2,
                            Author = "George Orwell",
                            Genre = "Dystopian",
                            Price = 8.99m,
                            Title = "1984"
                        },
                        new
                        {
                            BookId = 3,
                            Author = "Harper Lee",
                            Genre = "Classic",
                            Price = 12.99m,
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            BookId = 4,
                            Author = "Jane Austen",
                            Genre = "Romance",
                            Price = 9.99m,
                            Title = "PrBookIde and Prejudice"
                        },
                        new
                        {
                            BookId = 5,
                            Author = "J.D. Salinger",
                            Genre = "Fiction",
                            Price = 11.99m,
                            Title = "The Catcher in the Rye"
                        },
                        new
                        {
                            BookId = 6,
                            Author = "J.R.R. Tolkien",
                            Genre = "Fantasy",
                            Price = 14.99m,
                            Title = "The Hobbit"
                        },
                        new
                        {
                            BookId = 7,
                            Author = "Herman Melville",
                            Genre = "Adventure",
                            Price = 13.99m,
                            Title = "Moby Dick"
                        },
                        new
                        {
                            BookId = 8,
                            Author = "Leo Tolstoy",
                            Genre = "Historical",
                            Price = 19.99m,
                            Title = "War and Peace"
                        },
                        new
                        {
                            BookId = 9,
                            Author = "Homer",
                            Genre = "Epic",
                            Price = 15.99m,
                            Title = "The Odyssey"
                        },
                        new
                        {
                            BookId = 10,
                            Author = "Fyodor Dostoevsky",
                            Genre = "Psychological",
                            Price = 17.99m,
                            Title = "Crime and Punishment"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
